Validation
Patfarmurs/myblog pull request #3
Opened 2023-07-15 22:32 UTC by Patfarmurs

### In this Pull Request I did the following

-Added the validations for:

-   User model:

      - Name must not be blank.
      - PostsCounter must be an integer greater than or equal to zero.
-  Post model:

      - Title must not be blank.
      - Title must not exceed 250 characters.
      - CommentsCounter must be an integer greater than or equal to zero.
      - LikesCounter must be an integer greater than or equal to zero.

-  Add unit specs for all of your models' methods and validations.

2023-07-15 23:23 UTC, Lucas-Masaba requested changes
# Hello @Patfarmurs  👋 , 

Good job so far! 👍 
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights 🍾 
- Linter checks passing :heavy_check_mark: 
- Descriptive pull request message :writing_hand: 
- Proper use of gitflow :surfer: 

## Required Changes ♻️
_Check the comments under the review._

- [x] Your MIT license link on your `README.md` leads to a 404 page. Please fix that.
![image](https://github.com/Patfarmurs/myblog/assets/45460192/3701e52e-c3e1-412c-9e61-827eae914bca)


## Optional suggestions 💭 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Lucas-Masaba in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-15 23:23 UTC, Lucas-Masaba commented on spec/models/comment_spec.rb
- [ ] When I run your tests I gett the following errors for `like` and `comment` spec tests
![image](https://github.com/Patfarmurs/myblog/assets/45460192/b53ec613-b9fb-422f-a225-8435cb219b58)

- [ ] I do not see tests for the `update_comments_counter` method in the `comment` spec. Please add a test for this method because it is seen in your `comment `model

2023-07-15 23:23 UTC, Lucas-Masaba commented on spec/models/post_spec.rb
- [ ] I do not see tests for the `update_posts_counter` method in the `post` spec. Please add a test for this method because it is seen in your `post `model

2023-07-15 23:23 UTC, Lucas-Masaba commented on spec/models/like_spec.rb
- [ ] I do not see tests for the `update_likes_counter` method in the `like` spec. Please add a test for this method because it is seen in your `like `model

2023-07-18 19:22 UTC, cynthiainga approved these changes
Hi @Patfarmurs, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] All tests are passing ✔️ 
- [ ] No linters errors ✔️ 
- [ ] Correct Gitflow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-18 23:10 UTC, Patfarmurs commented
Thank you @cynthiainga

2023-07-18 23:12 UTC, merged