Integration specs
Patfarmurs/myblog pull request #8
Opened 2023-08-04 08:09 UTC by Patfarmurs

## In This milestone I : 
>-  Create integration tests for all of the views used in my project.

2023-08-04 09:07 UTC, danmainah requested changes
Hi @Patfarmurs and @ehmaddd , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Added tests for all the pages using the correct format.
✔️  Used Capybara to write integration tests for each view.


# Required Changes ♻️

- [ ] @Team kindly consider ensuring all tests are passing after implementing the changes requested.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-08-04 09:07 UTC, danmainah commented on app/controllers/posts_controller.rb
> +    @user = User.includes(:posts, :comments).find(params[:user_id])
- [x] @Patfarmurs and @ehmaddd great work trying to fix N + 1 problem, however, I would suggest a more neat way of doing it `@posts = @user.posts.includes(:comments)`, you can also reference the user using current_user method eg `@user = current_user`, also dont forget to add  include the screenshots of your app's logs before and after the fix in your PR description

2023-08-04 09:07 UTC, danmainah commented on spec/views/users/users_show_spec.rb
> +    end
- [x] @Team great work adding tests for the user show page however this test doesn't test if the page displays both name and profile picture it just tests the profile picture and title of the first post, kindly consider adding a test to ascertain the username is getting displayed.

2023-08-04 09:07 UTC, danmainah commented on spec/views/users/users_show_spec.rb
> +  end
- [x] @Team great work on your user show page tests, however, you forgot to add a test that ascertains the user is taken to the post index page if the user clicks on the `See all posts` button
![image](https://github.com/Patfarmurs/myblog/assets/61408860/4ce673b5-1df4-4d71-93af-a8184e0b9d47)

2023-08-04 09:07 UTC, danmainah commented on spec/views/posts/posts_index_spec.rb
> +    end
- [x] @Team great work adding tests for the post index page however you forgot to add a test that asserts a user can see a section for pagination if there are more posts than fit on the view.
![image](https://github.com/Patfarmurs/myblog/assets/61408860/c6c4f7e1-b5e9-4e32-a16d-9f338ae150f5)

2023-08-04 09:07 UTC, danmainah commented on spec/views/posts/posts_show_spec.rb
> +    end
- [ ] @Team kindly change this test from testing if the username is seen to the author's username is seen as per the project requirement
![image](https://github.com/Patfarmurs/myblog/assets/61408860/4e243273-da06-43b9-a501-4b34ff5ddc70)

- [ ] @Team you also forgot to include the tests below, kindly consider adding them.
 

- I can see the username of each commentor.
- I can see the comment each commentor left.

![image](https://github.com/Patfarmurs/myblog/assets/61408860/88c387ff-7d7f-42ff-b2a6-809d4ce65f3b)

2023-08-04 09:07 UTC, danmainah commented on spec/views/posts/posts_show_spec.rb
> +    end
- [ ] @team kindly remove this test since you don't have that functionality on your post-show page.

2023-08-04 09:07 UTC, danmainah commented on spec/views/posts/posts_show_spec.rb
> +    end
- [ ] @team kindly remove this test since you don't have that functionality on your post-show page.

2023-08-04 09:07 UTC, danmainah commented on spec/views/posts/posts_show_spec.rb
> +    end
- [ ] @team kindly remove this test since you don't have that functionality on your post-show page.

2023-08-05 20:45 UTC, DuaneDave requested changes
Hi @Patfarmurs and @danmainah 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ Good job so far with the index and show page tests

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-05 20:45 UTC, DuaneDave commented on spec/views/users/users_show_spec.rb
> +  end
As previously requested, you are expected to write a test to ascertain that when the see-all post link is created, it redirects the user to the post index page. I recommend adding this in order to satisfy the milestone requirements

2023-08-05 20:45 UTC, DuaneDave commented on spec/views/posts/posts_index_spec.rb
> +      expect(page).to have_current_path(user_post_path(@user.id, @first_post.id))
As previously requested, you're expected to have a test to ascertain that there is a section for pagination on the screen. Consider adding maybe a button, name it pagination and complete the test case in order to satisfy the milestone requirement.

2023-08-05 20:45 UTC, DuaneDave commented on spec/views/posts/posts_show_spec.rb
> +      expect(page).to have_content(user_name)
As previously requested, there are still two missing tests to ascertain that a user can see the username of each commentor and that the comment each commentor left. Please include this integration test in order to meet up the requirement.

2023-08-05 23:24 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @Patfarmurs , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] All unit tests pass with green check marks :white_check_mark: 
- [x] Rspec ruby gem is used for testing the application :white_check_mark:  
- [x] Implemented all the changes from the previous reviewer :white_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-06 09:41 UTC, Patfarmurs commented
Thanks a lot, @Felix45

2023-08-06 09:42 UTC, merged